-- local dap = require('dap')

-- dap.adapters.python {
--   {
--     type = 'python';
-- 		request = 'launch';
-- 		name = "Launch file";

-- 		pythonPath = function()
--       -- debugpy supports launching an application with a different interpreter then the one used to launch debugpy itself.
--       -- The code below looks for a `venv` or `.venv` folder in the current directly and uses the python within.
--       -- You could adapt this - to for example use the `VIRTUAL_ENV` environment variable.
--       local cwd = vim.fn.getcwd()

--       if vim.fn.executable(cwd .. '/venv/bin/python') then
--         return cwd .. '/venv/bin/python'
--       elseif vim.fn.executable(cwd .. '/.venv/bin/python') then
--         return cwd .. '/.venv/bin/python'
--       else
--         return '/usr/bin/python'
--       end
--     end;
-- 	},
-- }

-- require("dapui").setup({
--   icons = {
--     expanded = "⯆",
--     collapsed = "⯈",
--     circular = "↺"
--   },
--   mappings = {
--     expand = "<CR>",
--     open = "o",
--     remove = "d"
--   },
--   sidebar = {
--     elements = {
--       -- You can change the order of elements in the sidebar
--       "scopes",
--       "stacks",
--       "watches"
--     },
--     width = 40,
--     position = "left" -- Can be "left" or "right"
--   },
--   tray = {
--     elements = {
--       "repl"
--     },
--     height = 10,
--     position = "bottom" -- Can be "bottom" or "top"
--   },
--   floating = {
--     max_height = nil, -- These can be integers or a float between 0 and 1.
--     max_width = nil   -- Floats will be treated as percentage of your screen.
--   }
-- })
