require('indent_blankline').setup({
	debug = true,
	viewport_buffer = 20,
	use_treesitter = true,
	char = '▏',
	show_first_indent_level = true,
	show_trailing_blankline_indent = false,
	show_current_context = true,
	show_current_context_start = true,
	context_higlight_list = { 'healthSuccess' },
	show_end_of_line = false,
	context_char = '▏',
	context_patterns = {
		'class',
		'return',
		'function',
		'method',
		'^if',
		'^do',
		'^switch',
		'^while',
		'jsx_element',
		'^for',
		'^object',
		'^table',
		'block',
		'arguments',
		'if_statement',
		'else_clause',
		'jsx_element',
		'jsx_self_closing_element',
		'try_statement',
		'catch_clause',
		'import_statement',
		'operation_type',
	},
	buftype_exclude = {
		'nofile',
		'terminal',
	},
	filetype_exclude = {
		'help',
		'man',
		'log',
		'packer',
		'alpha',
		'NvimTree',
		'Trouble',
		'floatline',
	},
})
