name: Stylua check

on:
  push:
    branches: 'master'
  pull_request:
    branches: 'master'

jobs:
  format:
    name: stylua
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Check Stylua Format
        uses: JohnnyMorganz/stylua-action@1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --check -g '!compiled.lua' --color always lua/
